import { afterEach, expect, test, vi } from "vitest";
import { PanelIntent } from "../../../../src/renderer/board/panel-intent";
afterEach(() => vi.useRealTimers());
test("hover intent switches after 120ms and tolerates the gap to the panel", () => {
  vi.useFakeTimers();
  const panel = new PanelIntent();
  const row = { focus: vi.fn() } as unknown as HTMLElement;
  const off = panel.subscribe(vi.fn());
  panel.enter("one", row);
  vi.advanceTimersByTime(399);
  expect(panel.getSnapshot()).toBeUndefined();
  vi.advanceTimersByTime(1);
  expect(panel.getSnapshot()?.id).toBe("one");
  panel.enter("two", row);
  vi.advanceTimersByTime(119);
  expect(panel.getSnapshot()?.id).toBe("one");
  vi.advanceTimersByTime(1);
  expect(panel.getSnapshot()?.id).toBe("two");
  panel.leave();
  vi.advanceTimersByTime(249);
  panel.hold();
  vi.advanceTimersByTime(1000);
  expect(panel.getSnapshot()?.id).toBe("two");
  panel.enter("two", row);
  panel.leave();
  vi.advanceTimersByTime(250);
  expect(panel.getSnapshot()).toBeUndefined();
  off();
  panel.dispose();
});
test("pinning ignores hover, other rows and leave; close restores focus; dragging prevents opens", () => {
  vi.useFakeTimers();
  const panel = new PanelIntent();
  const focus = vi.fn();
  const row = { focus } as unknown as HTMLElement;
  panel.enter("one", row);
  panel.pin("one", row);
  panel.enter("two", row);
  panel.pin("two", row);
  panel.leave();
  vi.runAllTimers();
  expect(panel.getSnapshot()).toMatchObject({ id: "one", pinned: true });
  panel.drag(true);
  expect(focus).toHaveBeenCalledOnce();
  panel.enter("two", row);
  panel.pin("two", row);
  vi.runAllTimers();
  expect(panel.getSnapshot()).toBeUndefined();
  panel.drag(false);
  panel.enter("two", row);
  panel.dispose();
  vi.runAllTimers();
  expect(panel.getSnapshot()).toBeUndefined();
});
