import type { BoardRow } from "./board.d";

export function sampleRows(now: number): BoardRow[] {
  return [
    {
      kind: "sample",
      id: "build",
      repository: "foom",
      branch: "feat/terminal-tabs",
      agent: "Codex",
      state: "working",
      reason: "Building terminal navigation · sample: output",
      rate: 2200,
      waitingSince: now,
      seen: false,
      tail: ["Checking keyboard navigation…", "Building renderer"],
    },
    {
      kind: "sample",
      id: "check",
      repository: "foom",
      branch: "fix/resize",
      agent: "Antigravity",
      state: "quiet_ok",
      reason: "Output stopped · no decisive evidence",
      rate: 0,
      waitingSince: now,
      seen: false,
      tail: ["Resize tests complete.", "Reviewing results…"],
    },
    {
      kind: "sample",
      id: "done",
      repository: "observatory",
      branch: "docs/setup",
      agent: "Claude Code",
      state: "done",
      reason: "Finished successfully · exit: 0",
      rate: 0,
      waitingSince: now,
      seen: false,
      tail: ["Documentation updated.", "Process exited (0)"],
    },
    {
      kind: "sample",
      id: "failed",
      repository: "observatory",
      branch: "fix/search",
      agent: "Codex",
      state: "failed",
      reason: "Tests failed · exit: 1",
      rate: 0,
      waitingSince: now,
      seen: false,
      tail: ["FAIL search returns matching results", "Process exited (1)"],
    },
    {
      kind: "sample",
      id: "server",
      repository: "observatory",
      branch: "feat/dashboard",
      agent: "Shell",
      state: "quiet_ok",
      reason: "Development server is ready · pattern: listening",
      rate: 0,
      waitingSince: now,
      seen: false,
      tail: ["Server listening on localhost:3000", "Ready"],
    },
    {
      kind: "sample",
      id: "approve",
      repository: "observatory",
      branch: "feat/export",
      agent: "Claude Code",
      state: "needs_input",
      reason: "Waiting for approval · pattern: (y/n)",
      rate: 0,
      waitingSince: now - 45000,
      seen: false,
      tail: ["Export is ready.", "Continue? (y/n)"],
    },
    ...["index", "lint", "package"].map(
      (name): BoardRow => ({
        id: name,
        kind: "sample",
        repository: "launchpad",
        branch: `chore/${name}`,
        agent: "Codex",
        state: "working",
        reason: `${name} in progress · sample: output`,
        rate: 1200,
        waitingSince: now,
        seen: false,
        tail: [`Running ${name}…`],
      }),
    ),
  ];
}

/** Repository insertion order and row insertion order are independent of verdicts. */
