import { afterEach, expect, test, vi } from "vitest";
import { ConfirmationArming } from "../../../../src/main/confirmations/arming";
import type { ArmedConfirmation } from "../../../../src/shared/confirmation";
afterEach(() => vi.useRealTimers());
test("binds unpredictable nonces to the exact action/target, rejecting forgery, early clicks and replay", async () => {
  vi.useFakeTimers();
  let time = 0;
  const publish = vi.fn<(arm: ArmedConfirmation | null) => void>();
  const arms = new ConfirmationArming(publish, () => time);
  expect(arms.confirm("forged", "stop:t1")).toBe(false);
  const pending = arms.ask(arms.begin(), "stop:t1", "Click again to stop");
  const arm = publish.mock.calls[0]?.[0];
  expect(arm?.nonce).toMatch(/^[\da-f-]{36}$/);
  expect(arms.confirm("forged", "stop:t1")).toBe(false);
  time = 299;
  expect(arms.confirm(arm?.nonce, "stop:t1")).toBe(false);
  time = 300;
  expect(arms.confirm(arm?.nonce, "stop:t2")).toBe(false);
  expect(arms.confirm(arm?.nonce, "remove:t1")).toBe(false);
  expect(arms.confirm(arm?.nonce, "stop:t1")).toBe(true);
  await expect(pending).resolves.toBe(true);
  expect(arms.confirm(arm?.nonce, "stop:t1")).toBe(false);
  expect(publish).toHaveBeenLastCalledWith(null, true);
  const next = arms.ask(arms.begin(), "stop:t1", "Stop");
  expect(publish.mock.calls.at(-1)?.[0]?.nonce).not.toBe(arm?.nonce);
  arms.cancel();
  await expect(next).resolves.toBe(false);
});
test("deadline is inclusive but delayed timers cannot extend it; cancel invalidates in-flight preparation", async () => {
  vi.useFakeTimers();
  let time = 0;
  const publish = vi.fn<(arm: ArmedConfirmation | null) => void>();
  const arms = new ConfirmationArming(publish, () => time);
  const generation = arms.begin();
  const first = arms.ask(generation, "a", "Remove");
  let nonce = publish.mock.calls.at(-1)?.[0]?.nonce;
  time = 3000;
  expect(arms.confirm(nonce, "a")).toBe(true);
  await expect(first).resolves.toBe(true);
  const late = arms.ask(generation, "a", "Remove");
  nonce = publish.mock.calls.at(-1)?.[0]?.nonce;
  time = 6001;
  expect(arms.confirm(nonce, "a")).toBe(false);
  await expect(late).resolves.toBe(false);
  await expect(arms.ask(generation, "a", "stale")).resolves.toBe(false);
  const timeout = arms.ask(arms.begin(), "b", "Remove");
  vi.advanceTimersByTime(3000);
  await expect(timeout).resolves.toBe(false);
  const replaced = arms.ask(arms.begin(), "c", "Remove");
  const second = arms.ask(arms.begin(), "d", "Remove");
  await expect(replaced).resolves.toBe(false);
  arms.cancel();
  await expect(second).resolves.toBe(false);
});

test("the production clock enforces the minimum interval", async () => {
  const publish = vi.fn<(arm: ArmedConfirmation | null) => void>();
  const arming = new ConfirmationArming(publish);
  const pending = arming.ask(arming.begin(), "remove:repo", "Remove");
  const arm = publish.mock.calls[0]?.[0];
  expect(arming.confirm(arm?.nonce, arm?.target)).toBe(false);
  arming.cancel();
  await expect(pending).resolves.toBe(false);
});
